### ISSUE TITLE
Raspberry pi pico support

### ISSUE THREAD

**Issue by iMrDJAi** [AbkarinoMHM/PS4SysconTools#10]
Raspberry Pi Pico is an affordable alternative to Teensy. [Xbox360 nand flasher](https://github.com/walczakp/xbox360-flasher) that is originally designed for Teensy has proven to be working with the Pico. Should we expect it to normally work? Are there any plans to support it?

**Comment by ZerausYnohtna** [comment]
Could you Program the Raspberry Pi Pi to work with PS4 Syscom Flasher and PS4 Syscom Tools?

**Comment by AbkarinoMHM** [comment]
Hey, It is in our plan, we will use donations that we received to by some Raspberry Pi Pico dev boards to test.
