### ISSUE TITLE
restore to R5F101LLAFB

### ISSUE THREAD

**Issue by shoyrock** [AbkarinoMHM/PS4SysconTools#12]
hey just wanted to know if there's a way to write syscon back to an R5F101LLAFB, I've been trying without any lock just wanted to know if I'm doing something wrong

**Comment by AbkarinoMHM** [comment]
Hey, if you mean a stock chip, then our tool will not help you, since the stock chips i snot protected by the key that we are using to access original PS4 Syscon.
You can find any cheap renesas flasher or build your own with just 2 diodes and USB to TTL converter.

**Comment by shoyrock** [comment]
got it thanks for the help

**Comment by shoyrock** [comment]
> Hey, if you mean a stock chip, then our tool will not help you, since the stock chips i snot protected by the key that we are using to access original PS4 Syscon. You can find any cheap renesas flasher or build your own with just 2 diodes and USB to TTL converter.

hey I tried looking up how to go about doing this but I wasn't able to find anything about it online, would you be able to post a link to 2 diodes and USB to TTL converter?

**Comment by AbkarinoMHM** [comment]
Yea, you can refer to this project, it is open source hardware/software for renesas mcu
https://github.com/msalau/rl78flash

**Comment by AbkarinoMHM** [comment]
You can refer to this simple diagram for hw flasher:

![IMG_5991](https://github.com/AbkarinoMHM/PS4SysconTools/assets/14132937/df42285f-b4bc-4ee3-be54-c87d3e883409)

for me I was using mode 3 and it was working fine.
