### ISSUE TITLE
Debug wiring help.

### ISSUE THREAD

**Issue by Doyle4** [AbkarinoMHM/PS4SysconTools#14]
Seen on youtube users have debug enabled but no tut shows how this is done. They mention a pin needs lifting and can be put back when done. Question is, which pin needs lifting? Do you dump first, lift pin and enable? Some help/advise be amazing.

**Comment by AbkarinoMHM** [comment]
Hi,
You need only to lift the glitch pin which is pin 15 on slim/pro syscons or pin 22 on fat syscons, then after you enable syscon debug mode you can solder it back and no need to lift it again.

**Comment by Doyle4** [comment]
Thank you.

**Comment by AbkarinoMHM** [comment]
You are always welcome.
