### ISSUE TITLE
Will be open sourced the micrcontroller app?

### ISSUE THREAD

**Issue by WGR7** [AbkarinoMHM/PS4SysconTools#20]
Hi,

Is in your plans opensource the micrcontroller app?

Regards.

**Comment by ableto288** [comment]
https://twitter.com/Valys30/status/1744388449778450631

**Comment by ebedevelopment** [comment]
> https://twitter.com/Valys30/status/1744388449778450631

Hi,

It is another project not our work.

Best regards,
Abkarino

**Comment by AbkarinoMHM** [comment]
> https://twitter.com/Valys30/status/1744388449778450631

Hi,

It is another project not our work.

Best regards,
Abkarino
