### ISSUE TITLE
r5f100fcafp (Renesas RL78/G13) 44pin

### ISSUE THREAD

**Issue by sedeco99** [AbkarinoMHM/PS4SysconTools#24]
hi i need read this r5f100fcafp (Renesas RL78/G13) 44pin  by your software  but no connect  can any tell me thanks

**Comment by ebedevelopment** [comment]
Hi,
you should use any RL78 flasher for that, our tools only support original PS4 Syscon (RL78/G13) chips not a stock chip like in your case.
you can refer to this project that will help you: https://github.com/msalau/rl78flash

Best regards,
Abkarino

**Comment by AbkarinoMHM** [comment]
Hi,
you should use any RL78 flasher for that, our tools only support original PS4 Syscon (RL78/G13) chips not a stock chip like in your case.
you can refer to this project that will help you: https://github.com/msalau/rl78flash

Best regards,
Abkarino

**Comment by sedeco99** [comment]
hello thanks my dear  i thing rl78/g13 all same  to read   because all programmer can flash and write to chip but no programmer 
can read this   thanks to you AbkarinoMHM  me  egypt  ahmed

**Comment by MohamedHassanNasr** [comment]
you are always welcome Ahmed, thanks so much for your too.

**Comment by MohamedHassanNasr** [comment]
by the way reading feature is limited to specific RL78/G13 boot ROM version 3.03 and also with specific unlock code :NotUsed:, that is why i said it will not support blank chip unless it have the same requirements.

**Comment by sedeco99** [comment]
> by the way reading feature is limited to specific RL78/G13 boot ROM version 3.03 and also with specific unlock code :NotUsed:, that is why i said it will not support blank chip unless it have the same requirements.

thanks my dear some programmer like jlink flasher  read  but very high price  and some programmer in car dash do this

**Comment by riegaz** [comment]
How likely it is that another car dash RL78 uses OCD 3.03? What do you think? Is there any other tool around that would let me read a R5F100? It would be great if you could point me in the right direction.

Anything else I could do to read the flash of a R5F100?

**Comment by sedeco99** [comment]
hello   lock here  and install software you can see the programmer can read flash and code tor this ics 
https://www.segger.com/products/debug-probes/j-trace/models/j-trace-pro/
