### ISSUE TITLE
Error while writing

### ISSUE THREAD

**Issue by F3lix2k02** [AbkarinoMHM/PS4SysconTools#25]
thanks for your great tool but using teensy2.0++ v1.60 with hex file v2.00 reading sycon ok but writing NVS/SNVS only error “process failed” at offset 0x060000 or program not responding with syscon tool v1.5 while writing NVS/SNVS

**Comment by truevapor** [comment]
@F3lix2k02 @AbkarinoMHM @egycnq Did you manage to solve the problem? I am able to read the dump and Rewrite Boot0 Blocks, but I can't write the modified dump to Syscon. Reading the chip onboard. Tryin v2.1.0 and v1.6
