### ISSUE TITLE
Teensy 2.0

### ISSUE THREAD

**Issue by war10ck87** [AbkarinoMHM/PS4SysconTools#26]
Hi, I'm wondering if we could use Teensy 2.0 instead of Teensy 2.0++ or Teensy 4.0. I noticed there are differences in specifications and performance, but I'd like to explore if Teensy 2.0 could still meet the project requirements without necessarily upgrading to a newer version.

**Comment by MohamedHassanNasr** [comment]
Hi, sorry teensy 2.0 is not supported right now, because it only offer 1 serial/usb port, which currently is not enough for the current setup, but maybe we can support it later, by rewrite our flasher code to support only 1 serial/USB port.
