### ISSUE TITLE
Anyway to recover?

### ISSUE THREAD

**Issue by TheCroupier74** [AbkarinoMHM/PS4SysconTools#28]
Hi I was using V1.60 and successfully backed up my syscon.

I then tried to write back the backup but the tool immediately froze, non responsive. I waited a while then had to force quit.

I tried to reconnect to read the chip but it fails.
looks like the chip erased with no data written.

I understand your tool cannot write to a blank chip?
What are my options to recover from this issue and in the future is there anyway to prevent these random freezing of your software?

Thanks.

**Comment by alpay35** [comment]
Have you tried programming externally by inserting the sysconn chip?

**Comment by TheCroupier74** [comment]
No, on board with pin 22 lifted.
I think my cheapest option is to buy a used syscon, BWE’s Syscon rebuilder could probably fix it but it’s $175, I could just buy another PS4 for that cost.
Luckily I have a good backup of my Syscon.

**Comment by AbkarinoMHM** [comment]
Sorry to hear that, but in worest case, if you have a good backup, you can write it back to any syscon chip eather blank or originally locked one, and it will work without any issue.

**Comment by TheCroupier74** [comment]
Yes I have backup, I dump 2 times, verify they are good then made extra copies. Will look for a cheap replacement Syscon chip.

**Comment by AbkarinoMHM** [comment]
Great to hear that, you can get a any chip from a dead board it will be very cheap and easy to find.
