### ISSUE TITLE
Teensy 4.1Diagram

### ISSUE THREAD

**Issue by Naughtyangel103** [AbkarinoMHM/PS4SysconTools#39]
Hello, I have found that images in Teensy 4.1 folder are wrong. Correct image is as below, if possible to add wiring diagram for this please.
![Teensy 4_1](https://github.com/user-attachments/assets/c3be8dc8-32c5-4f2b-9c4b-9d108afebed2)

**Comment by AbkarinoMHM** [comment]
Hi,
Thanks for your feedback, you can still use wiring digram from teensy 4.0 because teensy 4.0 and 4.1 share the same setup.
Abkarino
