### ISSUE TITLE
Support for UNO R3

### ISSUE THREAD

**Issue by chronoss09** [AbkarinoMHM/PS4SysconTools#4]
hi !!!

It will me possibl to add a support for [UNO R3](https://docs.arduino.cc/hardware/uno-rev3) in the futur ?

**Comment by AbkarinoMHM** [comment]
Hi,
Sorry Arduino UNO R3 can not be supported since it does not have access to hardware serial port and also it will not be stable to use soft serial.

**Comment by chronoss09** [comment]
Ok thanks a lot and thanks for a great job you make 🥇
