### ISSUE TITLE
Teensy 4.1 .hex

### ISSUE THREAD

**Issue by M4n0zz** [AbkarinoMHM/PS4SysconTools#5]
Can you also compile the project for Teensy 4.1 please? I am pretty sure no changes are required in the source!

**Comment by AbkarinoMHM** [comment]
You can try to flash Teensy 4.0 hex file directly sine both Teensy 4.0 and 4.1 share the same MCU and pinout used in our project, then if it fail please tell me.

**Comment by AbkarinoMHM** [comment]
Hey, i have updated our hardware flasher code to support Teensy 4.1 so you can test it if you want.
