### ISSUE TITLE
RP2040 board firmware suggestion.

### ISSUE THREAD

**Issue by rutdarkronin** [AbkarinoMHM/PS4SysconTools#8]
Hello! Thank you for your brilliant work!
Can we possibly have version for Raspberry Pi nano 2040, the very same that used to glitch Nintendo Switch? They're fast, cheap and powerfull and far more common than teensy 2.0++, which is really hard to find these days.
Thank you!

**Comment by AbkarinoMHM** [comment]
Hey, It is in our plan, we will use donations that we received to by some Raspberry Pi Pico dev boards to test.
